apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartz-postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/quartz-postgres"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quartz-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  