apiVersion: v1
kind: Service
metadata:
  name: quartz-postgres-service
spec:
  selector:
    app: quartz-postgres-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31079
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: quartz-demo
spec:
  selector:
    app: quartz-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  type: NodePort
  